#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [ ! -e "pnpm-lock.yaml" ]; then
    echo "pnpm-lock.yaml is missing! `pnpm install` and `git commit --ammend` to fix."
    exit 1
fi

pnpm run type-check

